var annotated_dup =
[
    [ "LangYa", "namespace_lang_ya.html", [
      [ "SentryLib", "namespace_lang_ya_1_1_sentry_lib.html", [
        [ "ApplicationInfo", "struct_lang_ya_1_1_sentry_lib_1_1_application_info.html", "struct_lang_ya_1_1_sentry_lib_1_1_application_info" ],
        [ "ArmorPlateInfo", "struct_lang_ya_1_1_sentry_lib_1_1_armor_plate_info.html", "struct_lang_ya_1_1_sentry_lib_1_1_armor_plate_info" ],
        [ "CommandLineArguments", "struct_lang_ya_1_1_sentry_lib_1_1_command_line_arguments.html", "struct_lang_ya_1_1_sentry_lib_1_1_command_line_arguments" ],
        [ "Configurator", "class_lang_ya_1_1_sentry_lib_1_1_configurator.html", "class_lang_ya_1_1_sentry_lib_1_1_configurator" ],
        [ "Connection", "class_lang_ya_1_1_sentry_lib_1_1_connection.html", "class_lang_ya_1_1_sentry_lib_1_1_connection" ],
        [ "Controller", "class_lang_ya_1_1_sentry_lib_1_1_controller.html", "class_lang_ya_1_1_sentry_lib_1_1_controller" ],
        [ "DeserializableContent", "class_lang_ya_1_1_sentry_lib_1_1_deserializable_content.html", "class_lang_ya_1_1_sentry_lib_1_1_deserializable_content" ],
        [ "Device", "class_lang_ya_1_1_sentry_lib_1_1_device.html", "class_lang_ya_1_1_sentry_lib_1_1_device" ],
        [ "LangYaConnection", "class_lang_ya_1_1_sentry_lib_1_1_lang_ya_connection.html", "class_lang_ya_1_1_sentry_lib_1_1_lang_ya_connection" ],
        [ "MemoryAccess", "class_lang_ya_1_1_sentry_lib_1_1_memory_access.html", "class_lang_ya_1_1_sentry_lib_1_1_memory_access" ],
        [ "MemoryIO", "class_lang_ya_1_1_sentry_lib_1_1_memory_i_o.html", "class_lang_ya_1_1_sentry_lib_1_1_memory_i_o" ],
        [ "MemoryView", "struct_lang_ya_1_1_sentry_lib_1_1_memory_view.html", "struct_lang_ya_1_1_sentry_lib_1_1_memory_view" ],
        [ "PingPongBuffer", "class_lang_ya_1_1_sentry_lib_1_1_ping_pong_buffer.html", "class_lang_ya_1_1_sentry_lib_1_1_ping_pong_buffer" ],
        [ "Position1", "struct_lang_ya_1_1_sentry_lib_1_1_position1.html", "struct_lang_ya_1_1_sentry_lib_1_1_position1" ],
        [ "Position2", "struct_lang_ya_1_1_sentry_lib_1_1_position2.html", "struct_lang_ya_1_1_sentry_lib_1_1_position2" ],
        [ "Position3", "struct_lang_ya_1_1_sentry_lib_1_1_position3.html", "struct_lang_ya_1_1_sentry_lib_1_1_position3" ],
        [ "Resource", "struct_lang_ya_1_1_sentry_lib_1_1_resource.html", "struct_lang_ya_1_1_sentry_lib_1_1_resource" ],
        [ "Sensor", "class_lang_ya_1_1_sentry_lib_1_1_sensor.html", "class_lang_ya_1_1_sentry_lib_1_1_sensor" ],
        [ "SerializableContent", "class_lang_ya_1_1_sentry_lib_1_1_serializable_content.html", "class_lang_ya_1_1_sentry_lib_1_1_serializable_content" ],
        [ "Serializer", "class_lang_ya_1_1_sentry_lib_1_1_serializer.html", "class_lang_ya_1_1_sentry_lib_1_1_serializer" ],
        [ "SerialNumbers", "struct_lang_ya_1_1_sentry_lib_1_1_serial_numbers.html", "struct_lang_ya_1_1_sentry_lib_1_1_serial_numbers" ],
        [ "SerialPort", "class_lang_ya_1_1_sentry_lib_1_1_serial_port.html", "class_lang_ya_1_1_sentry_lib_1_1_serial_port" ],
        [ "SerialPortInfo", "struct_lang_ya_1_1_sentry_lib_1_1_serial_port_info.html", "struct_lang_ya_1_1_sentry_lib_1_1_serial_port_info" ],
        [ "Table", "class_lang_ya_1_1_sentry_lib_1_1_table.html", "class_lang_ya_1_1_sentry_lib_1_1_table" ],
        [ "TCPConnection", "class_lang_ya_1_1_sentry_lib_1_1_t_c_p_connection.html", "class_lang_ya_1_1_sentry_lib_1_1_t_c_p_connection" ],
        [ "TripleBuffer", "class_lang_ya_1_1_sentry_lib_1_1_triple_buffer.html", "class_lang_ya_1_1_sentry_lib_1_1_triple_buffer" ],
        [ "UniqueBuffer", "class_lang_ya_1_1_sentry_lib_1_1_unique_buffer.html", "class_lang_ya_1_1_sentry_lib_1_1_unique_buffer" ],
        [ "Vector", "class_lang_ya_1_1_sentry_lib_1_1_vector.html", "class_lang_ya_1_1_sentry_lib_1_1_vector" ],
        [ "Vector2", "class_lang_ya_1_1_sentry_lib_1_1_vector2.html", "class_lang_ya_1_1_sentry_lib_1_1_vector2" ],
        [ "Vector3", "class_lang_ya_1_1_sentry_lib_1_1_vector3.html", "class_lang_ya_1_1_sentry_lib_1_1_vector3" ]
      ] ]
    ] ],
    [ "AutoAimerSoftwareControllerData", "struct_auto_aimer_software_controller_data.html", "struct_auto_aimer_software_controller_data" ],
    [ "AutoAimerSoftwareSensorData", "struct_auto_aimer_software_sensor_data.html", "struct_auto_aimer_software_sensor_data" ],
    [ "Data", "struct_data.html", "struct_data" ],
    [ "DecisionResource", "struct_decision_resource.html", null ],
    [ "DecisionResult", "struct_decision_result.html", null ],
    [ "EmbeddedSoftwareControllerData", "struct_embedded_software_controller_data.html", "struct_embedded_software_controller_data" ],
    [ "EmbeddedSoftwareSensorData", "struct_embedded_software_sensor_data.html", "struct_embedded_software_sensor_data" ],
    [ "NavigatorSoftwareControllerData", "struct_navigator_software_controller_data.html", "struct_navigator_software_controller_data" ],
    [ "NavigatorSoftwareSensorData", "struct_navigator_software_sensor_data.html", "struct_navigator_software_sensor_data" ],
    [ "RefereeSystemControllerData", "struct_referee_system_controller_data.html", "struct_referee_system_controller_data" ],
    [ "RefereeSystemSensorData", "struct_referee_system_sensor_data.html", "struct_referee_system_sensor_data" ],
    [ "SentryData", "struct_sentry_data.html", "struct_sentry_data" ]
];